<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PDFSignerLicenses">
		<xs:annotation>
			<xs:documentation>PDF Signer License File Schema</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Licenses">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Owner" type="xs:string" nillable="false"/>
							<xs:element name="MainVersion" type="xs:int" nillable="false"/>
              <xs:element name="KofaxSerial" type="xs:string" nillable="false"/>
              <xs:element name="AsyncOperation" type="xs:boolean" nillable="false"/>
              <xs:element name="ValidUntil" type="xs:date" nillable="false"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Signature" type="xs:string" nillable="false"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
