'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class XmlSchemas
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFSignerCommon.XmlSchemas", GetType(XmlSchemas).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''	&lt;xs:element name=&quot;PDFSignerConfig&quot;&gt;
        '''		&lt;xs:annotation&gt;
        '''			&lt;xs:documentation&gt;PDF Signer System Configuration File Schema&lt;/xs:documentation&gt;
        '''		&lt;/xs:annotation&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:sequence&gt;
        '''        &lt;xs:element name=&quot;GUILanguage&quot; type=&quot;xs:string&quot; nillable=&quot;false&quot;/&gt;
        '''      &lt;/xs:sequence&gt;
        '''		&lt;/xs:complexType&gt;
        '''	&lt;/xs:element&gt;
        '''&lt;/xs:schema&gt;.
        '''</summary>
        Public Shared ReadOnly Property PDFSignerConfig() As String
            Get
                Return ResourceManager.GetString("PDFSignerConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''	&lt;xs:element name=&quot;PDFSignerLicenses&quot;&gt;
        '''		&lt;xs:annotation&gt;
        '''			&lt;xs:documentation&gt;PDF Signer License File Schema&lt;/xs:documentation&gt;
        '''		&lt;/xs:annotation&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:sequence&gt;
        '''				&lt;xs:element name=&quot;Licenses&quot;&gt;
        '''					&lt;xs:complexType&gt;
        '''						&lt;xs:sequence&gt;
        '''							&lt;xs:element name=&quot;Owner&quot; type=&quot;xs:string&quot; nillable=&quot;false&quot;/&gt;
        '''							&lt;xs:el [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property PDFSignerLicense() As String
            Get
                Return ResourceManager.GetString("PDFSignerLicense", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
