'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GUIText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFSigner.GUIText", GetType(GUIText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Licensed user: {0}.
        '''</summary>
        Friend Shared ReadOnly Property About_End_User() As String
            Get
                Return ResourceManager.GetString("About_End_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tungsten Capture serial number: {0}.
        '''</summary>
        Friend Shared ReadOnly Property About_Serial_Number() As String
            Get
                Return ResourceManager.GetString("About_Serial_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property About_Version() As String
            Get
                Return ResourceManager.GetString("About_Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Completed() As String
            Get
                Return ResourceManager.GetString("Batch_State_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Error() As String
            Get
                Return ResourceManager.GetString("Batch_State_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In progress.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_In_Progress() As String
            Get
                Return ResourceManager.GetString("Batch_State_In_Progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Ready() As String
            Get
                Return ResourceManager.GetString("Batch_State_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reserved.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Reserved() As String
            Get
                Return ResourceManager.GetString("Batch_State_Reserved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suspended.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Suspended() As String
            Get
                Return ResourceManager.GetString("Batch_State_Suspended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property Batch_State_Unknown() As String
            Get
                Return ResourceManager.GetString("Batch_State_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (qualified).
        '''</summary>
        Friend Shared ReadOnly Property Cert_Qualified() As String
            Get
                Return ResourceManager.GetString("Cert_Qualified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch class.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Batch_Class() As String
            Get
                Return ResourceManager.GetString("Filter_Batch_Class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch creation date/time.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Batch_Creation_Date_Time() As String
            Get
                Return ResourceManager.GetString("Filter_Batch_Creation_Date_Time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch field.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Batch_Field() As String
            Get
                Return ResourceManager.GetString("Filter_Batch_Field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch name.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Batch_Name() As String
            Get
                Return ResourceManager.GetString("Filter_Batch_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Contains() As String
            Get
                Return ResourceManager.GetString("Filter_Contains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Filtering enabled.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Enabled_Window_Header() As String
            Get
                Return ResourceManager.GetString("Filter_Enabled_Window_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Equals to.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Equal_To() As String
            Get
                Return ResourceManager.GetString("Filter_Equal_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property Filter_False() As String
            Get
                Return ResourceManager.GetString("Filter_False", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Greater than.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Greater_Than() As String
            Get
                Return ResourceManager.GetString("Filter_Greater_Than", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has error?.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Has_Error() As String
            Get
                Return ResourceManager.GetString("Filter_Has_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Less than.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Less_Than() As String
            Get
                Return ResourceManager.GetString("Filter_Less_Than", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not equals to.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Not_Equal_To() As String
            Get
                Return ResourceManager.GetString("Filter_Not_Equal_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priority.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Priority() As String
            Get
                Return ResourceManager.GetString("Filter_Priority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Queue.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Queue() As String
            Get
                Return ResourceManager.GetString("Filter_Queue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan station ID.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Scan_Station_ID() As String
            Get
                Return ResourceManager.GetString("Filter_Scan_Station_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan user.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Scan_User() As String
            Get
                Return ResourceManager.GetString("Filter_Scan_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starts with.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Starts_With() As String
            Get
                Return ResourceManager.GetString("Filter_Starts_With", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Station ID.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Station_ID() As String
            Get
                Return ResourceManager.GetString("Filter_Station_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Status() As String
            Get
                Return ResourceManager.GetString("Filter_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Filter_True() As String
            Get
                Return ResourceManager.GetString("Filter_True", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch in progress - {0}.
        '''</summary>
        Friend Shared ReadOnly Property Header_Batch_In_Progress() As String
            Get
                Return ResourceManager.GetString("Header_Batch_In_Progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open batch ({0} batch(es)).
        '''</summary>
        Friend Shared ReadOnly Property Header_Batch_Open_Batch_Count() As String
            Get
                Return ResourceManager.GetString("Header_Batch_Open_Batch_Count", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page {0}, Image {1}.
        '''</summary>
        Friend Shared ReadOnly Property Page_Display_Name() As String
            Get
                Return ResourceManager.GetString("Page_Display_Name", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
