'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFSigner.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certification clause added to PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Added_Certification_Clause_To_PDF() As String
            Get
                Return ResourceManager.GetString("Added_Certification_Clause_To_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Adding certification clause to PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Adding_Certification_Clause_To_PDF() As String
            Get
                Return ResourceManager.GetString("Adding_Certification_Clause_To_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All signable documents have signature or are rejected.
        '''Do you want to open the batch?.
        '''</summary>
        Friend Shared ReadOnly Property All_Documents_Signed() As String
            Get
                Return ResourceManager.GetString("All_Documents_Signed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All required documents in the batch are processed.
        '''Do you want to close the batch?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_All_Documents_Processed() As String
            Get
                Return ResourceManager.GetString("Ask_All_Documents_Processed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to close the batch?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Close_Batch() As String
            Get
                Return ResourceManager.GetString("Ask_Close_Batch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete all saved filters?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Delete_All_Saved_Filters() As String
            Get
                Return ResourceManager.GetString("Ask_Delete_All_Saved_Filters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the selected page?
        '''This will remove all existing signatures from the selected document..
        '''</summary>
        Friend Shared ReadOnly Property Ask_Delete_And_Remove_Signatures() As String
            Get
                Return ResourceManager.GetString("Ask_Delete_And_Remove_Signatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the selected page?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Delete_Page() As String
            Get
                Return ResourceManager.GetString("Ask_Delete_Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the selected filter?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Delete_Saved_Filter() As String
            Get
                Return ResourceManager.GetString("Ask_Delete_Saved_Filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove all existing signatures from the selected document?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Remove_Signatures() As String
            Get
                Return ResourceManager.GetString("Ask_Remove_Signatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to rotate the selected page?
        '''This will remove all existing signatures from the selected document..
        '''</summary>
        Friend Shared ReadOnly Property Ask_Rotate_And_Remove_Signatures() As String
            Get
                Return ResourceManager.GetString("Ask_Rotate_And_Remove_Signatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to suspend the batch?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Suspend_Batch() As String
            Get
                Return ResourceManager.GetString("Ask_Suspend_Batch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch has unsigned documents requiring signing.
        '''Do you want to suspend the batch?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Suspend_Batch_With_Signable_Docs() As String
            Get
                Return ResourceManager.GetString("Ask_Suspend_Batch_With_Signable_Docs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch closed.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closed() As String
            Get
                Return ResourceManager.GetString("Batch_Closed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch closed and completed.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closed_Completed() As String
            Get
                Return ResourceManager.GetString("Batch_Closed_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch closed with at least one rejected document.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closed_Has_Rejected() As String
            Get
                Return ResourceManager.GetString("Batch_Closed_Has_Rejected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch closing.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closing() As String
            Get
                Return ResourceManager.GetString("Batch_Closing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch with rejected document closing.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closing_With_Rejected_PDF() As String
            Get
                Return ResourceManager.GetString("Batch_Closing_With_Rejected_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch with skipped document closing.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Closing_With_Skipped_PDF() As String
            Get
                Return ResourceManager.GetString("Batch_Closing_With_Skipped_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected batch is not available or cannot be opened..
        '''</summary>
        Friend Shared ReadOnly Property Batch_Not_Available() As String
            Get
                Return ResourceManager.GetString("Batch_Not_Available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch opened.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Opened() As String
            Get
                Return ResourceManager.GetString("Batch_Opened", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; batch suspended.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Suspended() As String
            Get
                Return ResourceManager.GetString("Batch_Suspended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Checking if PDF document can be opened.
        '''</summary>
        Friend Shared ReadOnly Property Check_PDF_Can_Be_Opened() As String
            Get
                Return ResourceManager.GetString("Check_PDF_Can_Be_Opened", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Checking encryption of PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Checking_PDF_Encryption() As String
            Get
                Return ResourceManager.GetString("Checking_PDF_Encryption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   &apos;{0}&apos; attachment prepared.
        '''</summary>
        Friend Shared ReadOnly Property Clause_Attachment_Prepared() As String
            Get
                Return ResourceManager.GetString("Clause_Attachment_Prepared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating certification clause.
        '''</summary>
        Friend Shared ReadOnly Property Creating_Certification_Clause() As String
            Get
                Return ResourceManager.GetString("Creating_Certification_Clause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected document cannot be signed as it is not identified (no form type is assigned)..
        '''</summary>
        Friend Shared ReadOnly Property Document_Not_Identified() As String
            Get
                Return ResourceManager.GetString("Document_Not_Identified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected document cannot be signed as its document class is not set up for signing in the Administration module..
        '''</summary>
        Friend Shared ReadOnly Property Document_Not_Setup_For_Signing() As String
            Get
                Return ResourceManager.GetString("Document_Not_Setup_For_Signing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rejected document (form type: &apos;{0}&apos;, ID: {1}).
        '''</summary>
        Friend Shared ReadOnly Property Document_Rejected() As String
            Get
                Return ResourceManager.GetString("Document_Rejected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error signing document (form type: &apos;{0}&apos;, ID: {1}): {2}.
        '''</summary>
        Friend Shared ReadOnly Property Document_Sign_Error() As String
            Get
                Return ResourceManager.GetString("Document_Sign_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Document_Sign_Exception() As String
            Get
                Return ResourceManager.GetString("Document_Sign_Exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signatures deleted from document (form type: &apos;{0}&apos;, ID: {1}).
        '''</summary>
        Friend Shared ReadOnly Property Document_Signatures_Removed() As String
            Get
                Return ResourceManager.GetString("Document_Signatures_Removed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document successfully signed (form type: &apos;{0}&apos;, ID: {1}, duration: {2}).
        '''</summary>
        Friend Shared ReadOnly Property Document_Signed() As String
            Get
                Return ResourceManager.GetString("Document_Signed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skipped signing document (form type: &apos;{0}&apos;, ID: {1}).
        '''</summary>
        Friend Shared ReadOnly Property Document_Skipped() As String
            Get
                Return ResourceManager.GetString("Document_Skipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrejected document (form type: &apos;{0}&apos;, ID: {1}).
        '''</summary>
        Friend Shared ReadOnly Property Document_Unrejected() As String
            Get
                Return ResourceManager.GetString("Document_Unrejected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in signed file: size of signed file ({0} bytes) is smaller or equals the size of the unsigned file ({1} bytes)..
        '''</summary>
        Friend Shared ReadOnly Property Error_File_Sizes_Identical() As String
            Get
                Return ResourceManager.GetString("Error_File_Sizes_Identical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF document has no attachments (certification clause is missing)!.
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Attachments_In_PDF() As String
            Get
                Return ResourceManager.GetString("Error_No_Attachments_In_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The cryptographic component did not return the clause content..
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Clause_Content_Returned() As String
            Get
                Return ResourceManager.GetString("Error_No_Clause_Content_Returned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document has no signature!.
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Signature_In_PDF() As String
            Get
                Return ResourceManager.GetString("Error_No_Signature_In_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The cryptographic component did not return the name of the signer..
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Signed_By_Returned() As String
            Get
                Return ResourceManager.GetString("Error_No_Signed_By_Returned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No signed file name returned by the cryptographic component..
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Signed_File_Name_Returned() As String
            Get
                Return ResourceManager.GetString("Error_No_Signed_File_Name_Returned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No signed file returned by the cryptographic component..
        '''</summary>
        Friend Shared ReadOnly Property Error_No_Signed_File_Returned() As String
            Get
                Return ResourceManager.GetString("Error_No_Signed_File_Returned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while opening batch &apos;{0}&apos;: {1}.
        '''</summary>
        Friend Shared ReadOnly Property Error_Opening_Batch() As String
            Get
                Return ResourceManager.GetString("Error_Opening_Batch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Error opening PDF document for validation: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Error_Opening_PDF_For_Validation() As String
            Get
                Return ResourceManager.GetString("Error_Opening_PDF_For_Validation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   The PDF document cannot be modified or encrypted, so the requested operation cannot be performed!.
        '''</summary>
        Friend Shared ReadOnly Property Error_PDF_Encrypted() As String
            Get
                Return ResourceManager.GetString("Error_PDF_Encrypted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot determine document name required for certification clause..
        '''</summary>
        Friend Shared ReadOnly Property Exception_Document_Name_Cannot_Be_Determined() As String
            Get
                Return ResourceManager.GetString("Exception_Document_Name_Cannot_Be_Determined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Singning personnel&apos;s name is not provied (signing certificate is not selected, or certificate doesn&apos;t contain a name, or the logged in user has no Full Name provided in the Active Directory)..
        '''</summary>
        Friend Shared ReadOnly Property Exception_Signer_Name_Not_Provided() As String
            Get
                Return ResourceManager.GetString("Exception_Signer_Name_Not_Provided", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while signing document: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Exception_Signing() As String
            Get
                Return ResourceManager.GetString("Exception_Signing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signing of document with .NET data type {0} is not implemented..
        '''</summary>
        Friend Shared ReadOnly Property Exception_Unknown_Document_Type() As String
            Get
                Return ResourceManager.GetString("Exception_Unknown_Document_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown metadata format ({0})..
        '''</summary>
        Friend Shared ReadOnly Property Exception_Unknown_Metadata_Format() As String
            Get
                Return ResourceManager.GetString("Exception_Unknown_Metadata_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to delete {0} after {1} retries: {2}.
        '''</summary>
        Friend Shared ReadOnly Property File_Delete_Error() As String
            Get
                Return ResourceManager.GetString("File_Delete_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to move {0} to {1} after {2} retries: {3}.
        '''</summary>
        Friend Shared ReadOnly Property File_Move_Error() As String
            Get
                Return ResourceManager.GetString("File_Move_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to read {0} after {1} retries: {2}.
        '''</summary>
        Friend Shared ReadOnly Property File_Read_Error() As String
            Get
                Return ResourceManager.GetString("File_Read_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to write {0} after {1} retries: {2}.
        '''</summary>
        Friend Shared ReadOnly Property File_Write_Error() As String
            Get
                Return ResourceManager.GetString("File_Write_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter already exists. Would you like to modify it?.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Already_Exists() As String
            Get
                Return ResourceManager.GetString("Filter_Already_Exists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition {0}: batch field must be entered when filter by is set to &apos;{1}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Filter_Batch_Field_Not_Set() As String
            Get
                Return ResourceManager.GetString("Filter_Batch_Field_Not_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition {0}: filter by criteria not selected..
        '''</summary>
        Friend Shared ReadOnly Property Filter_By_Criteria_Not_Set() As String
            Get
                Return ResourceManager.GetString("Filter_By_Criteria_Not_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Values in the &apos;Filter by&apos; column must be unique except for &apos;Batch class&apos; values, which can be added multiple times..
        '''</summary>
        Friend Shared ReadOnly Property Filter_By_Criteria_Not_Unique() As String
            Get
                Return ResourceManager.GetString("Filter_By_Criteria_Not_Unique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while loading filter &apos;{0}&apos;: {1}.
        '''</summary>
        Friend Shared ReadOnly Property Filter_Load_Error() As String
            Get
                Return ResourceManager.GetString("Filter_Load_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter name is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Filter_Name_Not_Provided() As String
            Get
                Return ResourceManager.GetString("Filter_Name_Not_Provided", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition {0}: filter relation not selected..
        '''</summary>
        Friend Shared ReadOnly Property Filter_Relation_Not_Set() As String
            Get
                Return ResourceManager.GetString("Filter_Relation_Not_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition {0}: selected filter by criteria does not support selected filter relation..
        '''</summary>
        Friend Shared ReadOnly Property Filter_Relation_Not_Supported() As String
            Get
                Return ResourceManager.GetString("Filter_Relation_Not_Supported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition {0}: filter value not set..
        '''</summary>
        Friend Shared ReadOnly Property Filter_Value_Not_Set() As String
            Get
                Return ResourceManager.GetString("Filter_Value_Not_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signing failed.
        '''</summary>
        Friend Shared ReadOnly Property Header_Sign_Error() As String
            Get
                Return ResourceManager.GetString("Header_Sign_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot find original PDF File generated by Tungsten Capture. Possible causes:
        '''1. Document was rejected before the PDF Generator queue
        '''2. Document is not yet identified
        '''3. PDF Generation was not enabled for the document class
        '''4. PDF file was deleted.
        '''</summary>
        Friend Shared ReadOnly Property Kofax_Generated_PDF_File_Not_Found() As String
            Get
                Return ResourceManager.GetString("Kofax_Generated_PDF_File_Not_Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The last page of a document cannot be deleted..
        '''</summary>
        Friend Shared ReadOnly Property Last_Page_Cannot_Be_Deleted() As String
            Get
                Return ResourceManager.GetString("Last_Page_Cannot_Be_Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error resetting layout to factory settings: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Layout_Reset_Error() As String
            Get
                Return ResourceManager.GetString("Layout_Reset_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please restart the application for layout changes to take effect..
        '''</summary>
        Friend Shared ReadOnly Property Layout_Reset_Restart_Needed() As String
            Get
                Return ResourceManager.GetString("Layout_Reset_Restart_Needed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Developer mode, production usage is not permitted!.
        '''</summary>
        Friend Shared ReadOnly Property License_Developer_Mode() As String
            Get
                Return ResourceManager.GetString("License_Developer_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This copy of the {0} module can only be used with the {1} serial number Tungsten Capture system!
        '''Serial number of the current system is: {2}.
        '''</summary>
        Friend Shared ReadOnly Property License_Serial_Mismatch() As String
            Get
                Return ResourceManager.GetString("License_Serial_Mismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logged in user: {0} ({1}\{2}).
        '''</summary>
        Friend Shared ReadOnly Property Logged_In_User() As String
            Get
                Return ResourceManager.GetString("Logged_In_User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Looking for signatures in PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Looking_For_Signatures_In_PDF() As String
            Get
                Return ResourceManager.GetString("Looking_For_Signatures_In_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} - {1}.
        '''</summary>
        Friend Shared ReadOnly Property Main_Window_Title() As String
            Get
                Return ResourceManager.GetString("Main_Window_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} custom module is not registered in the Tungsten Capture system. Use the Custom Module Manager in the Administration module..
        '''</summary>
        Friend Shared ReadOnly Property Module_Not_Registered() As String
            Get
                Return ResourceManager.GetString("Module_Not_Registered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1} started.
        '''</summary>
        Friend Shared ReadOnly Property Module_Version_Started() As String
            Get
                Return ResourceManager.GetString("Module_Version_Started", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1} stopped.
        '''</summary>
        Friend Shared ReadOnly Property Module_Version_Stopped() As String
            Get
                Return ResourceManager.GetString("Module_Version_Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No signing certificate selected..
        '''</summary>
        Friend Shared ReadOnly Property No_Signing_Certificate_Selected() As String
            Get
                Return ResourceManager.GetString("No_Signing_Certificate_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch contains exported documents only and will be closed..
        '''</summary>
        Friend Shared ReadOnly Property No_Unreleased_Documents() As String
            Get
                Return ResourceManager.GetString("No_Unreleased_Documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original document must be viewed for signing to commence..
        '''</summary>
        Friend Shared ReadOnly Property Original_Document_Must_Be_Viewed() As String
            Get
                Return ResourceManager.GetString("Original_Document_Must_Be_Viewed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}. page of document deleted (form type: &apos;{1}&apos;, ID: {2}).
        '''</summary>
        Friend Shared ReadOnly Property Page_Deleted() As String
            Get
                Return ResourceManager.GetString("Page_Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}. page of document rotated left (form type: &apos;{1}&apos;, ID: {2}).
        '''</summary>
        Friend Shared ReadOnly Property Page_Rotated_Left() As String
            Get
                Return ResourceManager.GetString("Page_Rotated_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}. page of document rotated right (form type: &apos;{1}&apos;, ID: {2}).
        '''</summary>
        Friend Shared ReadOnly Property Page_Rotated_Right() As String
            Get
                Return ResourceManager.GetString("Page_Rotated_Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document already has a signature thus it cannot be certified (attaching certification clause would invalidate existing signature)!.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Already_Signed() As String
            Get
                Return ResourceManager.GetString("PDF_Already_Signed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document can be opened.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Can_Be_Opened() As String
            Get
                Return ResourceManager.GetString("PDF_Can_Be_Opened", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document cannot be opened: {ex}.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Cannot_Be_Opened() As String
            Get
                Return ResourceManager.GetString("PDF_Cannot_Be_Opened", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot find original PDF File generated by Tungsten Capture (form type: {0})..
        '''</summary>
        Friend Shared ReadOnly Property PDF_File_Not_Found() As String
            Get
                Return ResourceManager.GetString("PDF_File_Not_Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document has attachment.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Has_Attachments() As String
            Get
                Return ResourceManager.GetString("PDF_Has_Attachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document has signature.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Has_Signature() As String
            Get
                Return ResourceManager.GetString("PDF_Has_Signature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   PDF document has no signatures.
        '''</summary>
        Friend Shared ReadOnly Property PDF_No_Signatures() As String
            Get
                Return ResourceManager.GetString("PDF_No_Signatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   The PDF document is not encrypted.
        '''</summary>
        Friend Shared ReadOnly Property PDF_Not_Encrypted() As String
            Get
                Return ResourceManager.GetString("PDF_Not_Encrypted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validating signed PDF document.
        '''</summary>
        Friend Shared ReadOnly Property PostProcess_Validating_Signed_PDF() As String
            Get
                Return ResourceManager.GetString("PostProcess_Validating_Signed_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post-process validation found no errors.
        '''</summary>
        Friend Shared ReadOnly Property PostProcess_Validation_Completed() As String
            Get
                Return ResourceManager.GetString("PostProcess_Validation_Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot find the registry entry for the Kofax ExePath. It&apos;s possible that Tungsten Capture is not installed on this machine..
        '''</summary>
        Friend Shared ReadOnly Property Registry_Kofax_Bin_Path_Not_Found() As String
            Get
                Return ResourceManager.GetString("Registry_Kofax_Bin_Path_Not_Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected document cannot be signed as the document or its pages are rejected..
        '''</summary>
        Friend Shared ReadOnly Property Rejected_Document_Cannot_Be_Signed() As String
            Get
                Return ResourceManager.GetString("Rejected_Document_Cannot_Be_Signed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected document cannot be skipped as the document or its pages are rejected..
        '''</summary>
        Friend Shared ReadOnly Property Rejected_Document_Cannot_Be_Skipped() As String
            Get
                Return ResourceManager.GetString("Rejected_Document_Cannot_Be_Skipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are documents with signing tasks still running. Please wait for them to complete..
        '''</summary>
        Friend Shared ReadOnly Property Signature_Tasks_Running() As String
            Get
                Return ResourceManager.GetString("Signature_Tasks_Running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reason for skipping document signature must be provided..
        '''</summary>
        Friend Shared ReadOnly Property Skip_Note_Required() As String
            Get
                Return ResourceManager.GetString("Skip_Note_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fatal error due to unhandled exception: {0}.
        '''</summary>
        Friend Shared ReadOnly Property Unhandled_Exception() As String
            Get
                Return ResourceManager.GetString("Unhandled_Exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validating PDF document before signing.
        '''</summary>
        Friend Shared ReadOnly Property Validating_PDF() As String
            Get
                Return ResourceManager.GetString("Validating_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Validating attachments in PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Validating_PDF_Attachments() As String
            Get
                Return ResourceManager.GetString("Validating_PDF_Attachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished validating PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Validating_PDF_Finished() As String
            Get
                Return ResourceManager.GetString("Validating_PDF_Finished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Validating signature in PDF document.
        '''</summary>
        Friend Shared ReadOnly Property Validating_PDF_Signature() As String
            Get
                Return ResourceManager.GetString("Validating_PDF_Signature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetting workspace for form {0} because of load error: {1}.
        '''</summary>
        Friend Shared ReadOnly Property Workspace_Load_Error() As String
            Get
                Return ResourceManager.GetString("Workspace_Load_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving workspace for form {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property Workspace_Save_Error() As String
            Get
                Return ResourceManager.GetString("Workspace_Save_Error", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
