'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class CommonRes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFSignerCommon.CommonRes", GetType(CommonRes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot determine executable path of default browser..
        '''</summary>
        Public Shared ReadOnly Property Browser_Path_Cannot_Be_Determined() As String
            Get
                Return ResourceManager.GetString("Browser_Path_Cannot_Be_Determined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to License file cannot be decrypted..
        '''</summary>
        Public Shared ReadOnly Property LicenseDecryptError() As String
            Get
                Return ResourceManager.GetString("LicenseDecryptError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license expired on {1}..
        '''</summary>
        Public Shared ReadOnly Property LicenseExpired() As String
            Get
                Return ResourceManager.GetString("LicenseExpired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file cannot be accesed for read..
        '''</summary>
        Public Shared ReadOnly Property LicenseFileCannotBeRead() As String
            Get
                Return ResourceManager.GetString("LicenseFileCannotBeRead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file cannot be found.
        '''
        '''The license file should be either in the same folder as the PDFSigner.exe or on the Tungsten share at &apos;{1}&apos;..
        '''</summary>
        Public Shared ReadOnly Property LicenseFileNotFound() As String
            Get
                Return ResourceManager.GetString("LicenseFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file is not a valid XML file (not well-formed)..
        '''</summary>
        Public Shared ReadOnly Property LicenseFileNotWellFormed() As String
            Get
                Return ResourceManager.GetString("LicenseFileNotWellFormed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file cannot be used with the current Tungsten Capture system (serial number mismatch)..
        '''</summary>
        Public Shared ReadOnly Property LicenseKofaxSerialMismatch() As String
            Get
                Return ResourceManager.GetString("LicenseKofaxSerialMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file has been tampered with (signature error)..
        '''</summary>
        Public Shared ReadOnly Property LicenseSignatureError() As String
            Get
                Return ResourceManager.GetString("LicenseSignatureError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file is not for the current application version..
        '''</summary>
        Public Shared ReadOnly Property LicenseVersionMismatch() As String
            Get
                Return ResourceManager.GetString("LicenseVersionMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; license file is invalid (schema error){1}.
        '''</summary>
        Public Shared ReadOnly Property XMLSchemaError() As String
            Get
                Return ResourceManager.GetString("XMLSchemaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line: {0}, Position: {1} - &quot;{2}&quot;.
        '''</summary>
        Public Shared ReadOnly Property XMLSchemaValidationError() As String
            Get
                Return ResourceManager.GetString("XMLSchemaValidationError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
