'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFSignerCommon.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save settings before exiting?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Save_Changes() As String
            Get
                Return ResourceManager.GetString("Ask_Save_Changes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The clause format is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Clause_Format_Missing() As String
            Get
                Return ResourceManager.GetString("Clause_Format_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the copying organization is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Copying_Organization_Missing() As String
            Get
                Return ResourceManager.GetString("Copying_Organization_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the copying regulation is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Copying_Regulation_Name_Missing() As String
            Get
                Return ResourceManager.GetString("Copying_Regulation_Name_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The URL of the copying regulation is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Copying_Regulation_URL_Missing() As String
            Get
                Return ResourceManager.GetString("Copying_Regulation_URL_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The version of the copying regulation is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Copying_Regulation_Version_Missing() As String
            Get
                Return ResourceManager.GetString("Copying_Regulation_Version_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The default cryptographic provider is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Crypto_Provider_Not_Selected() As String
            Get
                Return ResourceManager.GetString("Crypto_Provider_Not_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The cryptographic provider selected as default is not enabled..
        '''</summary>
        Friend Shared ReadOnly Property Default_Crypto_Provider_Not_Enabled() As String
            Get
                Return ResourceManager.GetString("Default_Crypto_Provider_Not_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The document viewer is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Document_Viewer_Not_Selected() As String
            Get
                Return ResourceManager.GetString("Document_Viewer_Not_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error writing index field &apos;{0}&apos;: {1}.
        '''</summary>
        Friend Shared ReadOnly Property Error_Writing_Index_Value() As String
            Get
                Return ResourceManager.GetString("Error_Writing_Index_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception occured while loading existing settings:
        '''{0}.
        '''</summary>
        Friend Shared ReadOnly Property Exception_Loading_Setup_Values() As String
            Get
                Return ResourceManager.GetString("Exception_Loading_Setup_Values", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided file name append text contains characters that are not allowed in file names..
        '''</summary>
        Friend Shared ReadOnly Property File_Append_Text_Invalid() As String
            Get
                Return ResourceManager.GetString("File_Append_Text_Invalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signed file naming method is not selected..
        '''</summary>
        Friend Shared ReadOnly Property File_Naming_Not_Selected() As String
            Get
                Return ResourceManager.GetString("File_Naming_Not_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If new file is to be created after signing then either the file name postfix (appeneded text) or the replacement extension (or both) must be provided..
        '''</summary>
        Friend Shared ReadOnly Property File_New_Parameters_Not_Set() As String
            Get
                Return ResourceManager.GetString("File_New_Parameters_Not_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided replacement extension contains characters that are not allowed in file names..
        '''</summary>
        Friend Shared ReadOnly Property File_Replacement_Extension_Invalid() As String
            Get
                Return ResourceManager.GetString("File_Replacement_Extension_Invalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property Header_Error() As String
            Get
                Return ResourceManager.GetString("Header_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while opening the selected file.
        '''</summary>
        Friend Shared ReadOnly Property Header_File_Open_Error() As String
            Get
                Return ResourceManager.GetString("Header_File_Open_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while saving the selected file.
        '''</summary>
        Friend Shared ReadOnly Property Header_File_Save_Error() As String
            Get
                Return ResourceManager.GetString("Header_File_Save_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error displaying Help topic.
        '''</summary>
        Friend Shared ReadOnly Property Header_Help_Display_Error() As String
            Get
                Return ResourceManager.GetString("Header_Help_Display_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset settings.
        '''</summary>
        Friend Shared ReadOnly Property Header_Reset_Settings() As String
            Get
                Return ResourceManager.GetString("Header_Reset_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save settings.
        '''</summary>
        Friend Shared ReadOnly Property Header_Save_Changes() As String
            Get
                Return ResourceManager.GetString("Header_Save_Changes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The field containing the bar code must be selected when signature is controlled by bar code content..
        '''</summary>
        Friend Shared ReadOnly Property Index_Bar_Code_Missing() As String
            Get
                Return ResourceManager.GetString("Index_Bar_Code_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If &apos;Allow skip required documents&apos; is enabled then the Skip note index field must be selected..
        '''</summary>
        Friend Shared ReadOnly Property Index_Skip_Note_Missing() As String
            Get
                Return ResourceManager.GetString("Index_Skip_Note_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If &apos;Create single-pass PAdES B-LTA&apos; is enabled, then following settings must be applied:
        '''- &apos;Create document time stamp&apos; enabled,
        '''- Revocation check must be set to OCSP..
        '''</summary>
        Friend Shared ReadOnly Property LTA_Signature_Config_Incorrect() As String
            Get
                Return ResourceManager.GetString("LTA_Signature_Config_Incorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MNB Signer authentication method is not selected..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_Auth_Method_Not_Selected() As String
            Get
                Return ResourceManager.GetString("MNBSigner_Auth_Method_Not_Selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username/password (Basic) authentication is only allowed over an HTTPS URL for the MNBSigner provider..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_Basic_Auth_Requires_Https() As String
            Get
                Return ResourceManager.GetString("MNBSigner_Basic_Auth_Requires_Https", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The domain name of the user used to connect to the MNB Signer web service must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_Domain_Missing() As String
            Get
                Return ResourceManager.GetString("MNBSigner_Domain_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password for the user used to connect to the MNB Signer web service must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_Password_Missing() As String
            Get
                Return ResourceManager.GetString("MNBSigner_Password_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MNB Signer URL is not provided..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_URL_Missing() As String
            Get
                Return ResourceManager.GetString("MNBSigner_URL_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URL must address &apos;http&apos; or &apos;https&apos; resource..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_URL_Not_Http() As String
            Get
                Return ResourceManager.GetString("MNBSigner_URL_Not_Http", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user name used to connect to the MNB Signer web service must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MNBSigner_UserName_Missing() As String
            Get
                Return ResourceManager.GetString("MNBSigner_UserName_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The domain name of the user used to connect to the MQFTP exchange directories must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MQ_Domain_Missing() As String
            Get
                Return ResourceManager.GetString("MQ_Domain_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The MQFTP folder for incoming files must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MQ_FolderIn_Missing() As String
            Get
                Return ResourceManager.GetString("MQ_FolderIn_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The MQFTP folder for outgoing files must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MQ_FolderOut_Missing() As String
            Get
                Return ResourceManager.GetString("MQ_FolderOut_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password for the user used to connect to the MQFTP exchange directories must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MQ_Password_Missing() As String
            Get
                Return ResourceManager.GetString("MQ_Password_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user name used to connect to the MQFTP exchange directories must be provided..
        '''</summary>
        Friend Shared ReadOnly Property MQ_UserName_Missing() As String
            Get
                Return ResourceManager.GetString("MQ_UserName_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At least one cryptographic provider must be enabled..
        '''</summary>
        Friend Shared ReadOnly Property No_Crypto_Provider_Enabled() As String
            Get
                Return ResourceManager.GetString("No_Crypto_Provider_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Streamer authorization code is not provided..
        '''</summary>
        Friend Shared ReadOnly Property PDFStreamer_AuthCode_Missing() As String
            Get
                Return ResourceManager.GetString("PDFStreamer_AuthCode_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Streamer configuration file is not provided..
        '''</summary>
        Friend Shared ReadOnly Property PDFStreamer_ConfigFile_Missing() As String
            Get
                Return ResourceManager.GetString("PDFStreamer_ConfigFile_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Streamer URL is not provided..
        '''</summary>
        Friend Shared ReadOnly Property PDFStreamer_URL_Missing() As String
            Get
                Return ResourceManager.GetString("PDFStreamer_URL_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy authentication mode is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Proxy_Auth_Method_Missing() As String
            Get
                Return ResourceManager.GetString("Proxy_Auth_Method_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy server must be provided as FQDN or IP address. Do not use &apos;http(s)://&apos; prefix and do not include the port..
        '''</summary>
        Friend Shared ReadOnly Property Proxy_Server_Invalid() As String
            Get
                Return ResourceManager.GetString("Proxy_Server_Invalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy server name or IP is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Proxy_Server_Missing() As String
            Get
                Return ResourceManager.GetString("Proxy_Server_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy user name must be provided if authentication method is set to &apos;user/password&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Proxy_User_Missing() As String
            Get
                Return ResourceManager.GetString("Proxy_User_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid index field selected in the signature setup of document class &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Publish_Invalid_Index_Field() As String
            Get
                Return ResourceManager.GetString("Publish_Invalid_Index_Field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No document class has signing enabled..
        '''</summary>
        Friend Shared ReadOnly Property Publish_No_Doc_Class_Has_Signing_Enabled() As String
            Get
                Return ResourceManager.GetString("Publish_No_Doc_Class_Has_Signing_Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to reset all settings?.
        '''</summary>
        Friend Shared ReadOnly Property Reset_Settings() As String
            Get
                Return ResourceManager.GetString("Reset_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The method for revocation checking is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Revocation_Method_Missing() As String
            Get
                Return ResourceManager.GetString("Revocation_Method_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The signature hash algorithm is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Signature_Hash_Algorithm_Missing() As String
            Get
                Return ResourceManager.GetString("Signature_Hash_Algorithm_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signature marker is not provided..
        '''</summary>
        Friend Shared ReadOnly Property Signature_Marker_Missing() As String
            Get
                Return ResourceManager.GetString("Signature_Marker_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid signature policy hash (not a valid Base64 encoded string)..
        '''</summary>
        Friend Shared ReadOnly Property Signature_Policy_Hash_Error() As String
            Get
                Return ResourceManager.GetString("Signature_Policy_Hash_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The time stamp hash algorithm is not selected..
        '''</summary>
        Friend Shared ReadOnly Property Time_Stamp_Hash_Algorithm_Missing() As String
            Get
                Return ResourceManager.GetString("Time_Stamp_Hash_Algorithm_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The URL for the TSA is not provided..
        '''</summary>
        Friend Shared ReadOnly Property TSA_URL_Missing() As String
            Get
                Return ResourceManager.GetString("TSA_URL_Missing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided URL is incomplete..
        '''</summary>
        Friend Shared ReadOnly Property URL_Not_Complete() As String
            Get
                Return ResourceManager.GetString("URL_Not_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot interpret settings due to XML schema error..
        '''</summary>
        Friend Shared ReadOnly Property XML_Schema_Error() As String
            Get
                Return ResourceManager.GetString("XML_Schema_Error", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
