Imports System.IO
Imports System.Text
Imports PDFSigner.My.Resources
Imports PDFSignerCommon

Friend Class SignatureOperation
    Friend Function SignDocument(ByRef Document As DocumentItem, FileToSign As Stream, CryptographicProviderSettings As CryptoProviderBase, SigningCertificate As SigningCertificate, DocumentSize As String, PartialCopyData As String, UserDisplayName As String) As SignatureResult
        Document.ErrorMessage = Nothing

        Dim preProcRes As PreProcessResult = Nothing
        Dim sigRes As New SignatureResult

        Try
            Dim errMsg As String

            ' getting unique ID based on index field value or the GUID generated by KC
            Document.KofaxDocumentGUID = GetDocumentUID(Document)

            ' ********** DELETING ANY POSSIBLE PRE-EXISTING CHANGES **********

            Dim docOp As New DocumentOperation
            docOp.DeleteSignature(Document, True)

            ' move back to the start of the stream
            FileToSign.Seek(0, SeekOrigin.Begin)

            Document.ProgressPercent = 10

            ' ********** PRE-PROCESSING PDF FILE **********

            ' creating PDF pre-process class instances
            Dim preProcReq As New PreProcessRequest
            With preProcReq
                ' getting file
                .DocItem = Document
                .FileToPreProcess = FileToSign
                .FileName = Path.GetFileName(Document.UnsignedFilePath)
                .CryptoProvider = CryptographicProviderSettings

                ' getting metadata
                .MetaDataSettings = GetMetaDataSettings(Document, DocumentSize)
                If SigningCertificate IsNot Nothing Then
                    .MetaDataSettings.SignerFullName = SigningCertificate.GetIssuedToName
                Else
                    .MetaDataSettings.SignerFullName = UserDisplayName
                End If
                .MetaDataSettings.PartialCopyData = Document.PartialCopyData

                Document.ProgressPercent = 20

                If String.IsNullOrEmpty(.MetaDataSettings.SignerFullName) Then
                    sigRes.ErrorMessage = Messages.Exception_Signer_Name_Not_Provided
                    sigRes.SignatureLog = sigRes.ErrorMessage
                    Return sigRes
                End If

                .MetaDataSettings.SignedFileName = Path.GetFileName(Document.SignedFilePath)
            End With

            Document.ProgressPercent = 30

            ' call PDF pre-processor
            Dim preProc As New PDFPreProcessor
            preProcRes = preProc.Process(preProcReq)

            Document.UnsignedFileSize = preProcRes.PreProcessedFileSize

            ' validating pre-process result 
            errMsg = preProcRes.Validate
            sigRes.SignatureLog = preProcRes.PreProcessLog
            If Not String.IsNullOrEmpty(errMsg) Then
                sigRes.ErrorMessage = errMsg
                sigRes.SignatureLog += errMsg + vbCrLf
                Return sigRes
            End If

            ' ********** END PRE-PROCESSING **********

            Document.ProgressPercent = 50

            ' ********** SIGNING PDF FILE **********

            ' creating signature request
            Dim sigReq As New SignatureRequest
            With sigReq
                .SignSettings = CryptographicProviderSettings
                .MetaDataSettings = preProcReq.MetaDataSettings
                .UnsignedFileName = Path.GetFileName(Document.UnsignedFilePath)
                .SigningCertificate = SigningCertificate
                .FileToSign = preProcRes.PreProcessedFile
                .DocItem = Document
            End With

            ' call external signing routine
            If TypeOf sigReq.SignSettings Is PDFSignerCryptoProvider Then
                Using sbb As New SBBPDF
                    sbb.Initialize(sigReq.SignSettings)
                    sigRes = sbb.SignDocument(sigReq)
                End Using
            End If
            If TypeOf sigReq.SignSettings Is PDFStreamerCryptoProvider Then
                Dim pdfstr As New PDFStreamer
                pdfstr.Initialize(sigReq.SignSettings)
                sigRes = pdfstr.SignDocumentStream(sigReq)
            End If
            If TypeOf sigReq.SignSettings Is MQFTPCryptoProvider Then
                Dim mq As New MQFTP
                mq.Initialize(sigReq.SignSettings)
                sigRes = mq.SignDocument(sigReq)
            End If
            If TypeOf sigReq.SignSettings Is MNBSignerCryptoProvider Then
                Dim mnb As New MNBSigner
                mnb.Initialize(sigReq.SignSettings)
                sigRes = mnb.SignDocument(sigReq)
            End If

            sigRes.SignedAt = Date.Now

            Document.ProgressPercent = 60

            ' validating signing result 
            errMsg = sigRes.Validate(Document)
            sigRes.SignatureLog = preProcRes.PreProcessLog + sigRes.SignatureLog
            If Not String.IsNullOrEmpty(errMsg) Then
                sigRes.ErrorMessage = errMsg
                sigRes.SignatureLog += errMsg + vbCrLf
                Return sigRes
            End If

            ' ********** END SIGNING PDF FILE **********

            Document.ProgressPercent = 70

            ' ********** BEGIN POST-SIGNING PDF FILE CHECK **********

            ' creating PDF post-process class instances
            Dim postProcReq As New PostProcessRequest
            Dim postProcRes As New PostProcessResult
            Dim postProc As New PDFPostProcessor

            With postProcReq
                .FileToPostProcess = sigRes.SignedFile
                .DocItem = Document
            End With

            ' call PDF post-processor
            postProcRes = postProc.Process(postProcReq)
            sigRes.SignatureLog += postProcRes.PostProcessLog

            ' validating post-process result 
            errMsg = postProcRes.Validate
            If Not String.IsNullOrEmpty(errMsg) Then
                sigRes.ErrorMessage = errMsg
                sigRes.SignatureLog += errMsg + vbCrLf
                Return sigRes
            End If

            ' ********** END POST-SIGNING PDF FILE CHECK **********

            Document.ProgressPercent = 80

            ' ********** SAVING FILES AND DATA **********

            sigRes.MetaDataContent = preProcRes.MetaDataContent

            ' creating files' paths
            Dim savePath As String = Path.GetDirectoryName(Document.UnsignedFilePath)
            Dim DetachedSignatureFilePath As String = Nothing
            If sigRes.SaveDetachedSignature Then
                DetachedSignatureFilePath = Path.Combine(savePath, sigRes.DetachedSignatureFileName)
            End If
            Dim MetaDataFilePath As String = Nothing
            If sigRes.SaveMetaDataAsFile Then
                MetaDataFilePath = Path.Combine(savePath, sigRes.MetaDataFileName)
            End If

            ' saving files
            Dim fileOp As New FileOperation
            Using DestinationFS As New FileStream(Document.SignedFilePath, FileMode.Create, FileAccess.Write, FileShare.None)
                sigRes.SignedFile.Seek(0, SeekOrigin.Begin)
                sigRes.SignedFile.CopyTo(DestinationFS)
            End Using
            If Not String.IsNullOrEmpty(sigRes.DetachedSignatureFileName) Then fileOp.WriteAllBytesWhenAvailable(DetachedSignatureFilePath, sigRes.DetachedSignature)
            If Not String.IsNullOrEmpty(sigRes.MetaDataFileName) Then File.WriteAllText(MetaDataFilePath, sigRes.MetaDataContent, Encoding.UTF8)

            Document.ProgressPercent = 90

            ' setting CSSs and indexes in Kofax DB
            With Document
                SetCSSValue(.KofaxElement, CSS.IsDocumentSigned, "1")
                SetCSSValue(.KofaxElement, CSS.SignedFilePath, Document.SignedFilePath)
                SetCSSValue(.KofaxElement, CSS.DetachedSignatureFilePath, DetachedSignatureFilePath)
                SetCSSValue(.KofaxElement, CSS.ClauseFilePath, MetaDataFilePath)
                SetCSSValue(.KofaxElement, CSS.ClauseContent, sigRes.MetaDataContent)
                SetCSSValue(.KofaxElement, CSS.SignatureLogContent, sigRes.SignatureLog)
                SetCSSValue(.KofaxElement, CSS.SignedFileDateTime, File.GetLastWriteTime(Document.SignedFilePath))
                SetCSSValue(.KofaxElement, CSS.UnsignedFileDateTime, File.GetLastWriteTime(Document.UnsignedFilePath))

                If Not String.IsNullOrWhiteSpace(.SetupData.IndexIsSigned) Then
                    SetIndexValue(.KofaxElement, .SetupData.IndexIsSigned, "1")
                End If
                If Not String.IsNullOrWhiteSpace(.SetupData.IndexSignedDateTime) Then
                    SetIndexValue(.KofaxElement, .SetupData.IndexSignedDateTime, sigRes.SignedAt)
                End If
                If Not String.IsNullOrWhiteSpace(.SetupData.IndexSignedBy) Then
                    SetIndexValue(.KofaxElement, .SetupData.IndexSignedBy, Environment.UserDomainName + "\" + Environment.UserName)
                End If
                If Not String.IsNullOrWhiteSpace(.SetupData.IndexSignatureValidUntil) Then
                    SetIndexValue(.KofaxElement, .SetupData.IndexSignatureValidUntil, sigRes.SignatureExpiration)
                End If

                .KofaxElement("Completed") = "1"
                .KofaxElement("Indexed") = "1"

                .SignedFilePath = Document.SignedFilePath
                .DetachedSignatureFilePath = DetachedSignatureFilePath
                .ClauseFilePath = MetaDataFilePath
                .ClauseContent = sigRes.MetaDataContent
            End With

            ' ********** END SAVING FILES AND DATA **********

            Document.IconType = IconType.SignedDocument
            Document.IsSigned = True

            Return sigRes

        Catch ex As Exception
            Dim docOp As New DocumentOperation
            Try
                docOp.DeleteSignature(Document, True)
            Catch
            End Try

            sigRes.ErrorMessage = ex.Message
            sigRes.SignatureLog += ex.ToString
            sigRes.ExceptionText = ex.ToString
            Return sigRes

        Finally
            If FileToSign IsNot Nothing Then
                FileToSign.Close()
                FileToSign.Dispose()

                If TypeOf FileToSign Is FileStream Then
                    Dim tempFile As String = CType(FileToSign, FileStream).Name
                    If File.Exists(tempFile) Then File.Delete(tempFile)
                End If
            End If

            ' deterministically release the signed-file stream (MNB MemoryTributary / MQFTP FileStream);
            ' SBB and PDFStreamer return the input stream, which is disposed above
            If sigRes IsNot Nothing AndAlso sigRes.SignedFile IsNot Nothing AndAlso sigRes.SignedFile IsNot FileToSign Then
                sigRes.SignedFile.Dispose()
                sigRes.SignedFile = Nothing
            End If

            Document.ProgressPercent = 100
        End Try

    End Function

    Friend Function GetCertificatesFromMyWinCertStore(QualifiedCertificatesOnly As Boolean) As List(Of SigningCertificate)
        Using sbb As New SBBPDF
            Return sbb.GetCertificatesFromStore(QualifiedCertificatesOnly)
        End Using
    End Function

    Private Function GetMetaDataSettings(Document As DocumentItem, DocumentSize As String) As MetaData
        Dim res As New MetaData
        Dim docName As String = Nothing

        If Not String.IsNullOrEmpty(GetIndexValue(Document.KofaxElement, Document.SetupData.IndexDocumentName)) Then
            docName = GetIndexValue(Document.KofaxElement, Document.SetupData.IndexDocumentName) + " azonosítójú irat"
        End If
        If String.IsNullOrEmpty(docName) AndAlso Document.SetupData.DocumentNameFromFormType Then docName = Document.FormTypeName
        If String.IsNullOrEmpty(docName) Then docName = Document.SetupData.DocumentNameDefault
        If String.IsNullOrEmpty(docName) Then Throw New ArgumentException(Messages.Exception_Document_Name_Cannot_Be_Determined)

        res.DocumentName = docName
        res.DocumentSize = DocumentSize
        res.OrganizationName = Document.SetupData.ConvertingOrganization
        res.SystemNameAndVersion = KofaxRegistry.KofaxVersion
        res.RegulationName = Document.SetupData.ConvertingRegulationName
        res.RegulationURL = Document.SetupData.ConvertingRegulationURL
        res.RegulationVersion = Document.SetupData.ConvertingRegulationVersion
        res.ConversionDate = Date.Now
        res.Format = Document.SetupData.MetadataFormat
        res.SignaturePolicyURL = Document.SetupData.SignaturePolicyURL
        res.SignaturePolicyHash = Document.SetupData.SignaturePolicyHash
        res.SignaturePolicyOID = Document.SetupData.SignaturePolicyOID

        Return res
    End Function

    Friend Sub ActivateSBBLicense()
        Using e As New SBBPDF
            e.ActivateLicense()
        End Using
    End Sub

    Private Function GetDocumentUID(Document As DocumentItem) As String
        If Not String.IsNullOrWhiteSpace(Document.KofaxDocumentGUID) Then Return Document.KofaxDocumentGUID

        Dim res As String = Document.KofaxElement("BatchDocGUID").Replace("{", "").Replace("}", "")

        If Document.SetupData.DefaultCryptographicProvider = CryptoProviderType.MQFTP Then
            Dim uid As String = GetIndexValue(Document.KofaxElement, Document.SetupData.MQFTPProvider.IndexMQDocUID)
            If Not String.IsNullOrWhiteSpace(uid) Then res = uid
        End If

        Return res
    End Function
End Class
