'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PDFStreamerServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentCreateRequest", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentCreateRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthorizationKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CertificationMetaDataField As PDFStreamerServiceReference.CertifiedCopyMetadata
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentConfigurationFilenameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As PDFStreamerServiceReference.EmailData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PDFAttachmentsField() As PDFStreamerServiceReference.FileData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PDFDocumentField As PDFStreamerServiceReference.FileData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XMLDocumentField As PDFStreamerServiceReference.FileData
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthorizationKey() As String
            Get
                Return Me.AuthorizationKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuthorizationKeyField, value) <> true) Then
                    Me.AuthorizationKeyField = value
                    Me.RaisePropertyChanged("AuthorizationKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CertificationMetaData() As PDFStreamerServiceReference.CertifiedCopyMetadata
            Get
                Return Me.CertificationMetaDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CertificationMetaDataField, value) <> true) Then
                    Me.CertificationMetaDataField = value
                    Me.RaisePropertyChanged("CertificationMetaData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentConfigurationFilename() As String
            Get
                Return Me.DocumentConfigurationFilenameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentConfigurationFilenameField, value) <> true) Then
                    Me.DocumentConfigurationFilenameField = value
                    Me.RaisePropertyChanged("DocumentConfigurationFilename")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As PDFStreamerServiceReference.EmailData
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PDFAttachments() As PDFStreamerServiceReference.FileData()
            Get
                Return Me.PDFAttachmentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PDFAttachmentsField, value) <> true) Then
                    Me.PDFAttachmentsField = value
                    Me.RaisePropertyChanged("PDFAttachments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PDFDocument() As PDFStreamerServiceReference.FileData
            Get
                Return Me.PDFDocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PDFDocumentField, value) <> true) Then
                    Me.PDFDocumentField = value
                    Me.RaisePropertyChanged("PDFDocument")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TransactionID() As String
            Get
                Return Me.TransactionIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionIDField, value) <> true) Then
                    Me.TransactionIDField = value
                    Me.RaisePropertyChanged("TransactionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XMLDocument() As PDFStreamerServiceReference.FileData
            Get
                Return Me.XMLDocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XMLDocumentField, value) <> true) Then
                    Me.XMLDocumentField = value
                    Me.RaisePropertyChanged("XMLDocument")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CertifiedCopyMetadata", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CertifiedCopyMetadata
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AutomaticCopyField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopierNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopierOrganizationNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyCreationDateTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyingRegulationDocumentNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyingRegulationDocumentURLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyingRegulationDocumentVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyingSystemNameAndVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalDocumentNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalDocumentPhysicalSizeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PartialCopyDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecureDocumentControlField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecureViewBeforeSigningField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturePolicyHashField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturePolicyOIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturePolicyURLField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AutomaticCopy() As Boolean
            Get
                Return Me.AutomaticCopyField
            End Get
            Set
                If (Me.AutomaticCopyField.Equals(value) <> true) Then
                    Me.AutomaticCopyField = value
                    Me.RaisePropertyChanged("AutomaticCopy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopierName() As String
            Get
                Return Me.CopierNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopierNameField, value) <> true) Then
                    Me.CopierNameField = value
                    Me.RaisePropertyChanged("CopierName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopierOrganizationName() As String
            Get
                Return Me.CopierOrganizationNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopierOrganizationNameField, value) <> true) Then
                    Me.CopierOrganizationNameField = value
                    Me.RaisePropertyChanged("CopierOrganizationName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyCreationDateTime() As Date
            Get
                Return Me.CopyCreationDateTimeField
            End Get
            Set
                If (Me.CopyCreationDateTimeField.Equals(value) <> true) Then
                    Me.CopyCreationDateTimeField = value
                    Me.RaisePropertyChanged("CopyCreationDateTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyingRegulationDocumentName() As String
            Get
                Return Me.CopyingRegulationDocumentNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyingRegulationDocumentNameField, value) <> true) Then
                    Me.CopyingRegulationDocumentNameField = value
                    Me.RaisePropertyChanged("CopyingRegulationDocumentName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyingRegulationDocumentURL() As String
            Get
                Return Me.CopyingRegulationDocumentURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyingRegulationDocumentURLField, value) <> true) Then
                    Me.CopyingRegulationDocumentURLField = value
                    Me.RaisePropertyChanged("CopyingRegulationDocumentURL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyingRegulationDocumentVersion() As String
            Get
                Return Me.CopyingRegulationDocumentVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyingRegulationDocumentVersionField, value) <> true) Then
                    Me.CopyingRegulationDocumentVersionField = value
                    Me.RaisePropertyChanged("CopyingRegulationDocumentVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CopyingSystemNameAndVersion() As String
            Get
                Return Me.CopyingSystemNameAndVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyingSystemNameAndVersionField, value) <> true) Then
                    Me.CopyingSystemNameAndVersionField = value
                    Me.RaisePropertyChanged("CopyingSystemNameAndVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OriginalDocumentName() As String
            Get
                Return Me.OriginalDocumentNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalDocumentNameField, value) <> true) Then
                    Me.OriginalDocumentNameField = value
                    Me.RaisePropertyChanged("OriginalDocumentName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OriginalDocumentPhysicalSize() As String
            Get
                Return Me.OriginalDocumentPhysicalSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalDocumentPhysicalSizeField, value) <> true) Then
                    Me.OriginalDocumentPhysicalSizeField = value
                    Me.RaisePropertyChanged("OriginalDocumentPhysicalSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PartialCopyDescription() As String
            Get
                Return Me.PartialCopyDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PartialCopyDescriptionField, value) <> true) Then
                    Me.PartialCopyDescriptionField = value
                    Me.RaisePropertyChanged("PartialCopyDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecureDocumentControl() As Boolean
            Get
                Return Me.SecureDocumentControlField
            End Get
            Set
                If (Me.SecureDocumentControlField.Equals(value) <> true) Then
                    Me.SecureDocumentControlField = value
                    Me.RaisePropertyChanged("SecureDocumentControl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecureViewBeforeSigning() As Boolean
            Get
                Return Me.SecureViewBeforeSigningField
            End Get
            Set
                If (Me.SecureViewBeforeSigningField.Equals(value) <> true) Then
                    Me.SecureViewBeforeSigningField = value
                    Me.RaisePropertyChanged("SecureViewBeforeSigning")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SignaturePolicyHash() As String
            Get
                Return Me.SignaturePolicyHashField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturePolicyHashField, value) <> true) Then
                    Me.SignaturePolicyHashField = value
                    Me.RaisePropertyChanged("SignaturePolicyHash")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SignaturePolicyOID() As String
            Get
                Return Me.SignaturePolicyOIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturePolicyOIDField, value) <> true) Then
                    Me.SignaturePolicyOIDField = value
                    Me.RaisePropertyChanged("SignaturePolicyOID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SignaturePolicyURL() As String
            Get
                Return Me.SignaturePolicyURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturePolicyURLField, value) <> true) Then
                    Me.SignaturePolicyURLField = value
                    Me.RaisePropertyChanged("SignaturePolicyURL")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailData", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BCCAddressesField() As PDFStreamerServiceReference.EmailAddress
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BodyPlainTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCAddressesField() As PDFStreamerServiceReference.EmailAddress
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplyToAddressesField() As PDFStreamerServiceReference.EmailAddress
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToAddressesField() As PDFStreamerServiceReference.EmailAddress
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BCCAddresses() As PDFStreamerServiceReference.EmailAddress()
            Get
                Return Me.BCCAddressesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BCCAddressesField, value) <> true) Then
                    Me.BCCAddressesField = value
                    Me.RaisePropertyChanged("BCCAddresses")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BodyPlainText() As String
            Get
                Return Me.BodyPlainTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyPlainTextField, value) <> true) Then
                    Me.BodyPlainTextField = value
                    Me.RaisePropertyChanged("BodyPlainText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCAddresses() As PDFStreamerServiceReference.EmailAddress()
            Get
                Return Me.CCAddressesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCAddressesField, value) <> true) Then
                    Me.CCAddressesField = value
                    Me.RaisePropertyChanged("CCAddresses")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReplyToAddresses() As PDFStreamerServiceReference.EmailAddress()
            Get
                Return Me.ReplyToAddressesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplyToAddressesField, value) <> true) Then
                    Me.ReplyToAddressesField = value
                    Me.RaisePropertyChanged("ReplyToAddresses")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToAddresses() As PDFStreamerServiceReference.EmailAddress()
            Get
                Return Me.ToAddressesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToAddressesField, value) <> true) Then
                    Me.ToAddressesField = value
                    Me.RaisePropertyChanged("ToAddresses")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FileData", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FileData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContentField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreationDateTimeUTCField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameWithExtensionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Content() As Byte()
            Get
                Return Me.ContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContentField, value) <> true) Then
                    Me.ContentField = value
                    Me.RaisePropertyChanged("Content")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreationDateTimeUTC() As System.Nullable(Of Date)
            Get
                Return Me.CreationDateTimeUTCField
            End Get
            Set
                If (Me.CreationDateTimeUTCField.Equals(value) <> true) Then
                    Me.CreationDateTimeUTCField = value
                    Me.RaisePropertyChanged("CreationDateTimeUTC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileNameWithExtension() As String
            Get
                Return Me.FileNameWithExtensionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameWithExtensionField, value) <> true) Then
                    Me.FileNameWithExtensionField = value
                    Me.RaisePropertyChanged("FileNameWithExtension")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailAddress", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailAddress
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentCreateResponse", [Namespace]:="http://www.docsoft.hu/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentCreateResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentLogField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PDFDocumentField As PDFStreamerServiceReference.FileData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignerNameFromCertField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidUntilField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentLog() As String
            Get
                Return Me.DocumentLogField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentLogField, value) <> true) Then
                    Me.DocumentLogField = value
                    Me.RaisePropertyChanged("DocumentLog")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PDFDocument() As PDFStreamerServiceReference.FileData
            Get
                Return Me.PDFDocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PDFDocumentField, value) <> true) Then
                    Me.PDFDocumentField = value
                    Me.RaisePropertyChanged("PDFDocument")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SignerNameFromCert() As String
            Get
                Return Me.SignerNameFromCertField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignerNameFromCertField, value) <> true) Then
                    Me.SignerNameFromCertField = value
                    Me.RaisePropertyChanged("SignerNameFromCert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TransactionID() As String
            Get
                Return Me.TransactionIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionIDField, value) <> true) Then
                    Me.TransactionIDField = value
                    Me.RaisePropertyChanged("TransactionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValidUntil() As System.Nullable(Of Date)
            Get
                Return Me.ValidUntilField
            End Get
            Set
                If (Me.ValidUntilField.Equals(value) <> true) Then
                    Me.ValidUntilField = value
                    Me.RaisePropertyChanged("ValidUntil")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.docsoft.hu/", ConfigurationName:="PDFStreamerServiceReference.IPDFStreamer")>  _
    Public Interface IPDFStreamer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.docsoft.hu/IPDFStreamer/GetVersionInfo", ReplyAction:="http://www.docsoft.hu/IPDFStreamer/GetVersionInfoResponse")>  _
        Function GetVersionInfo() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.docsoft.hu/IPDFStreamer/CreatePDF", ReplyAction:="http://www.docsoft.hu/IPDFStreamer/CreatePDFResponse")>  _
        Function CreatePDF(ByVal req As PDFStreamerServiceReference.DocumentCreateRequest) As PDFStreamerServiceReference.DocumentCreateResponse
        
        'CODEGEN: Generating message contract since the wrapper name (StreamedDocumentCreateRequest) of message StreamedDocumentCreateRequest does not match the default value (CreatePDFStream)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.docsoft.hu/IPDFStreamer/CreatePDFStream", ReplyAction:="http://www.docsoft.hu/IPDFStreamer/CreatePDFStreamResponse")>  _
        Function CreatePDFStream(ByVal request As PDFStreamerServiceReference.StreamedDocumentCreateRequest) As PDFStreamerServiceReference.StreamedDocumentCreateResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="StreamedDocumentCreateRequest", WrapperNamespace:="http://www.docsoft.hu/", IsWrapped:=true)>  _
    Partial Public Class StreamedDocumentCreateRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public AuthorizationKey As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public DocumentConfigurationFilename As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public DocumentFileNameWithExtension As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public TransactionID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.docsoft.hu/", Order:=0)>  _
        Public DocumentStream As System.IO.Stream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthorizationKey As String, ByVal DocumentConfigurationFilename As String, ByVal DocumentFileNameWithExtension As String, ByVal TransactionID As String, ByVal DocumentStream As System.IO.Stream)
            MyBase.New
            Me.AuthorizationKey = AuthorizationKey
            Me.DocumentConfigurationFilename = DocumentConfigurationFilename
            Me.DocumentFileNameWithExtension = DocumentFileNameWithExtension
            Me.TransactionID = TransactionID
            Me.DocumentStream = DocumentStream
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="StreamedDocumentCreateResponse", WrapperNamespace:="http://www.docsoft.hu/", IsWrapped:=true)>  _
    Partial Public Class StreamedDocumentCreateResponse
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public DocumentFileNameWithExtension As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public DocumentLog As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public ErrorMessage As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public SignerNameFromCert As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public TransactionID As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.docsoft.hu/")>  _
        Public ValidUntil As System.Nullable(Of Date)
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.docsoft.hu/", Order:=0)>  _
        Public DocumentStream As System.IO.Stream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DocumentFileNameWithExtension As String, ByVal DocumentLog As String, ByVal ErrorMessage As String, ByVal SignerNameFromCert As String, ByVal TransactionID As String, ByVal ValidUntil As System.Nullable(Of Date), ByVal DocumentStream As System.IO.Stream)
            MyBase.New
            Me.DocumentFileNameWithExtension = DocumentFileNameWithExtension
            Me.DocumentLog = DocumentLog
            Me.ErrorMessage = ErrorMessage
            Me.SignerNameFromCert = SignerNameFromCert
            Me.TransactionID = TransactionID
            Me.ValidUntil = ValidUntil
            Me.DocumentStream = DocumentStream
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPDFStreamerChannel
        Inherits PDFStreamerServiceReference.IPDFStreamer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PDFStreamerClient
        Inherits System.ServiceModel.ClientBase(Of PDFStreamerServiceReference.IPDFStreamer)
        Implements PDFStreamerServiceReference.IPDFStreamer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetVersionInfo() As String Implements PDFStreamerServiceReference.IPDFStreamer.GetVersionInfo
            Return MyBase.Channel.GetVersionInfo
        End Function
        
        Public Function CreatePDF(ByVal req As PDFStreamerServiceReference.DocumentCreateRequest) As PDFStreamerServiceReference.DocumentCreateResponse Implements PDFStreamerServiceReference.IPDFStreamer.CreatePDF
            Return MyBase.Channel.CreatePDF(req)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PDFStreamerServiceReference_IPDFStreamer_CreatePDFStream(ByVal request As PDFStreamerServiceReference.StreamedDocumentCreateRequest) As PDFStreamerServiceReference.StreamedDocumentCreateResponse Implements PDFStreamerServiceReference.IPDFStreamer.CreatePDFStream
            Return MyBase.Channel.CreatePDFStream(request)
        End Function
        
        Public Function CreatePDFStream(ByVal AuthorizationKey As String, ByVal DocumentConfigurationFilename As String, ByRef DocumentFileNameWithExtension As String, ByRef TransactionID As String, ByRef DocumentStream As System.IO.Stream, <System.Runtime.InteropServices.OutAttribute()> ByRef ErrorMessage As String, <System.Runtime.InteropServices.OutAttribute()> ByRef SignerNameFromCert As String, <System.Runtime.InteropServices.OutAttribute()> ByRef ValidUntil As System.Nullable(Of Date)) As String
            Dim inValue As PDFStreamerServiceReference.StreamedDocumentCreateRequest = New PDFStreamerServiceReference.StreamedDocumentCreateRequest()
            inValue.AuthorizationKey = AuthorizationKey
            inValue.DocumentConfigurationFilename = DocumentConfigurationFilename
            inValue.DocumentFileNameWithExtension = DocumentFileNameWithExtension
            inValue.TransactionID = TransactionID
            inValue.DocumentStream = DocumentStream
            Dim retVal As PDFStreamerServiceReference.StreamedDocumentCreateResponse = CType(Me,PDFStreamerServiceReference.IPDFStreamer).CreatePDFStream(inValue)
            DocumentFileNameWithExtension = retVal.DocumentFileNameWithExtension
            ErrorMessage = retVal.ErrorMessage
            SignerNameFromCert = retVal.SignerNameFromCert
            TransactionID = retVal.TransactionID
            ValidUntil = retVal.ValidUntil
            DocumentStream = retVal.DocumentStream
            Return retVal.DocumentLog
        End Function
    End Class
End Namespace
